spring.application.name=fibrasnaturais

spring.sql.init.data-locations=classpath:data-dev.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

spring.cloud.gcp.credentials.location=file:${GCP_CREDENTIALS_PATH}

spring.cloud.gcp.project-id=${GCP_PROJETC_ID}

gcp.bucket.name=${GCP_BUCKET_NAME}